{% set name = "napari-tiler" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5b54535aa8e7ae06177b617eebeef765e03b0ff9be93f61b6773ad501918546e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python
  run:
    - importlib-metadata <4.3  # [py<38]
    - napari-plugin-engine >=0.2.0
    - napari-tools-menu >=0.1.7
    - numpy >=1.21.4
    - python
    - tiler >=0.4.1

test:
  imports:
    - napari_tiler
  commands:
    - pip list
    # - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/napari-tiler/
  summary: N-dimensional tiling and merging support for napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/tdmorello/napari-tiler

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tdmorello
